import { and, eq } from "drizzle-orm";
import { db } from "../server/db";
import { analysisRuns, roadmapProjects, roadmapTasks, roadmapWorkstreams } from "../shared/schema";

const RESOURCE_ID = "admin-roadmap-backbone";
const MODULE = "agent-bootstrap-backbone";
const BACKBONE_TITLE = "Admin Roadmap Backbone - Agent Bootstrap and Continuous Improvement";
const FRICTION_WORKSTREAM = "Friction Logging and Closed-Loop Improvement";
const THRESHOLD = Number(process.argv.find((arg) => arg.startsWith("--threshold="))?.split("=")[1] ?? 2);

function normalizeSummary(value: string) {
  return value.trim().replace(/\s+/g, " ");
}

function shortTitle(category: string, summary: string) {
  const compact = normalizeSummary(summary).slice(0, 72).trim();
  return `Friction Pattern - ${category}: ${compact}${compact.length >= 72 ? "..." : ""}`;
}

async function main() {
  const [project] = await db.select().from(roadmapProjects).where(eq(roadmapProjects.title, BACKBONE_TITLE));
  if (!project) throw new Error("Backbone project not found");
  const [workstream] = await db
    .select()
    .from(roadmapWorkstreams)
    .where(and(eq(roadmapWorkstreams.projectId, project.id), eq(roadmapWorkstreams.title, FRICTION_WORKSTREAM)));
  if (!workstream) throw new Error("Backbone friction workstream not found");

  const [runs, existingTasks] = await Promise.all([
    db.select().from(analysisRuns).where(and(eq(analysisRuns.resourceId, RESOURCE_ID), eq(analysisRuns.module, MODULE), eq(analysisRuns.action, "friction-observed"))),
    db.select().from(roadmapTasks).where(eq(roadmapTasks.projectId, project.id)),
  ]);

  const grouped = new Map<string, { category: string; summary: string; count: number; latestImpact: string | null; latestSource: string | null }>();
  for (const run of runs) {
    const metadata = (run.metadataJson ?? {}) as Record<string, unknown>;
    const summary = String(metadata.summary || "").trim();
    if (!summary) continue;
    const category = String(metadata.category || "general");
    const key = `${category}::${normalizeSummary(summary)}`;
    const current = grouped.get(key) ?? {
      category,
      summary,
      count: 0,
      latestImpact: null,
      latestSource: null,
    };
    current.count += 1;
    current.latestImpact = metadata.impact ? String(metadata.impact) : current.latestImpact;
    current.latestSource = metadata.source ? String(metadata.source) : current.latestSource;
    grouped.set(key, current);
  }

  let createdCount = 0;
  let updatedCount = 0;
  const eligible = Array.from(grouped.values()).filter((item) => item.count >= THRESHOLD);

  for (const item of eligible) {
    const title = shortTitle(item.category, item.summary);
    const description =
      `Generated from repeated backbone friction observations.\n\n` +
      `Category: ${item.category}\n` +
      `Occurrences: ${item.count}\n` +
      `Observed Friction: ${item.summary}\n` +
      `Latest Source: ${item.latestSource || "unknown"}\n` +
      `Latest Impact: ${item.latestImpact || "not captured"}\n\n` +
      `This task was generated by the bounded backbone sync and applies only to the admin roadmap backbone improvement loop.`;

    const existing = existingTasks.find((task) => task.workstreamId === workstream.id && task.title === title);
    if (!existing) {
      await db.insert(roadmapTasks).values({
        projectId: project.id,
        workstreamId: workstream.id,
        title,
        description,
        status: "todo",
        effort: "small",
        priority: item.category === "verification" ? "high" : "medium",
        dependencyTaskIds: [],
      });
      createdCount += 1;
      continue;
    }

    await db
      .update(roadmapTasks)
      .set({
        description,
        updatedAt: new Date(),
      })
      .where(eq(roadmapTasks.id, existing.id));
    updatedCount += 1;
  }

  const [run] = await db
    .insert(analysisRuns)
    .values({
      resourceId: RESOURCE_ID,
      module: MODULE,
      action: "friction-task-sync",
      success: 1,
      durationMs: 0,
      itemCount: eligible.length,
      metadataJson: {
        threshold: THRESHOLD,
        eligibleCount: eligible.length,
        createdCount,
        updatedCount,
      },
    })
    .returning();

  console.log(JSON.stringify({ runId: run.id, threshold: THRESHOLD, eligibleCount: eligible.length, createdCount, updatedCount }, null, 2));
  await db.$client.end();
}

main().catch(async (error) => {
  console.error(error);
  await db.$client.end();
  process.exit(1);
});
