/**
 * Statutory-records service — the ISSUANCE orchestrator (founder-os#9483).
 *
 * Ties the statutory-document generators to the two existing platform
 * mechanisms so nothing is re-built:
 *
 *   1. DEADLINE-IN-QUEUE — on intake we file an L3 agent-action carrying the
 *      record's `statutoryDeadline`. `rankQueue` (agent-action-service) already
 *      pins statutory-deadline items to the TOP of the chief-of-staff queue by
 *      soonest deadline, so the countdown is always visible; a near-deadline
 *      sweep surfaces a reminder ahead of the deadline.
 *   2. L3 PM-SIGN GATE — issuance actuates THROUGH `executeAction`, whose pure
 *      `evaluateGate` refuses an L3 action without a recorded human (PM)
 *      approval. Issuance is therefore structurally impossible without the sign
 *      — the exact same gate the whole platform uses (no parallel gate).
 *
 * The document is GENERATED by the route/caller (which gathers the live
 * financial data via the existing gatherers) and PASSED IN as `documentPayload`;
 * this service persists it, files the queue item, and owns the sign/issue
 * lifecycle. Keeping generation in the caller lets the issuance path depend only
 * on `statutory_records` + `agent_actions` — small, faithfully testable.
 *
 * Tenant isolation: every read/write is scoped by `associationId` derived from
 * the caller's session, never from the request body.
 */
import { and, desc, eq, gte, inArray, lte } from "drizzle-orm";
import { db } from "../db";
import {
  statutoryRecords,
  type StatutoryRecord,
  type StatutoryRecordType,
} from "@shared/schema";
import { computeStatutoryDeadline } from "./statutory-deadline-service";
import {
  fileAction,
  approveAction,
  executeAction,
  AgentActionError,
  type Approver,
} from "./agent-action-service";

export class StatutoryRecordError extends Error {
  constructor(
    message: string,
    public readonly code: string,
    public readonly httpStatus: number = 400,
  ) {
    super(message);
    this.name = "StatutoryRecordError";
  }
}

const ISSUE_ACTION_TYPE = "irreversible.issue_statutory_record";

function recordTypeLabel(t: StatutoryRecordType): string {
  switch (t) {
    case "resale_certificate":
      return "resale certificate (CGS §47-270)";
    case "estoppel_certificate":
      return "estoppel certificate";
    case "records_request":
      return "records-request response (CGS §47-260)";
    default:
      return t;
  }
}

export interface IntakeStatutoryRecordInput {
  associationId: string;
  recordType: StatutoryRecordType;
  requesterName: string;
  requesterEmail?: string | null;
  unitId?: string | null;
  personId?: string | null;
  /** When the request landed (day 0 of the deadline clock). Defaults to now. */
  receivedAt?: Date;
  expedited?: boolean;
  /** The generated statutory packet (built by the caller from live data). */
  documentPayload: unknown;
  /** Free-form agent identity that intaked the record (for the queue item). */
  createdByAgent?: string;
  /** Link to an existing §47-260 records-request lifecycle when one exists. */
  linkedRecordsRequestId?: string | null;
}

export interface IntakeStatutoryRecordResult {
  record: StatutoryRecord;
  agentActionId: string;
  deadlineAt: Date;
}

/**
 * Intake a statutory record: compute + pin its deadline, persist the packet,
 * and file the L3 sign-gated queue item. Returns the persisted record.
 */
export async function intakeStatutoryRecord(
  input: IntakeStatutoryRecordInput,
): Promise<IntakeStatutoryRecordResult> {
  if (!input.associationId) throw new StatutoryRecordError("associationId required", "VALIDATION");
  if (!input.recordType) throw new StatutoryRecordError("recordType required", "VALIDATION");
  if (!input.requesterName || !input.requesterName.trim()) {
    throw new StatutoryRecordError("requesterName required", "VALIDATION");
  }
  if (input.documentPayload == null) {
    throw new StatutoryRecordError("documentPayload required", "VALIDATION");
  }

  const receivedAt = input.receivedAt ?? new Date();
  const expedited = Boolean(input.expedited);
  const { deadlineAt, slaBusinessDays, statuteCitation } = computeStatutoryDeadline(
    input.recordType,
    receivedAt,
    expedited,
  );

  // Persist the generated record (awaiting the L3 sign).
  const [record] = await db
    .insert(statutoryRecords)
    .values({
      associationId: input.associationId,
      recordType: input.recordType,
      status: "generated",
      requesterName: input.requesterName,
      requesterEmail: input.requesterEmail ?? null,
      unitId: input.unitId ?? null,
      personId: input.personId ?? null,
      receivedAt,
      expedited: expedited ? 1 : 0,
      deadlineAt,
      slaBusinessDays,
      statuteCitation,
      documentPayload: input.documentPayload as any,
      linkedRecordsRequestId: input.linkedRecordsRequestId ?? null,
    })
    .returning();

  // File the L3 sign-gated queue item carrying the statutory deadline. This is
  // what pins the countdown to the top of the chief-of-staff queue.
  const action = await fileAction({
    associationId: input.associationId,
    actionType: ISSUE_ACTION_TYPE,
    reasoning:
      `Issue ${recordTypeLabel(input.recordType)} for ${input.requesterName}` +
      ` — due ${deadlineAt.toISOString().slice(0, 10)} (${statuteCitation}). ` +
      "Requires the PM's sign before issuance.",
    createdByAgent: input.createdByAgent ?? "statutory-records-intake",
    targetEntityType: "statutory_record",
    targetEntityId: record.id,
    payload: { recordType: input.recordType, statuteCitation },
    severity: "high",
    statutoryDeadline: deadlineAt,
  });

  const [updated] = await db
    .update(statutoryRecords)
    .set({ agentActionId: action.id, updatedAt: new Date() })
    .where(and(eq(statutoryRecords.id, record.id), eq(statutoryRecords.associationId, input.associationId)))
    .returning();

  return { record: updated, agentActionId: action.id, deadlineAt };
}

async function loadScoped(recordId: string, associationId: string): Promise<StatutoryRecord> {
  const [row] = await db
    .select()
    .from(statutoryRecords)
    .where(and(eq(statutoryRecords.id, recordId), eq(statutoryRecords.associationId, associationId)));
  if (!row) throw new StatutoryRecordError("statutory record not found", "NOT_FOUND", 404);
  return row;
}

/**
 * The PM SIGNS the record — records the L3 approval on the linked agent-action.
 * Sets the record to `signed`. Refuses if the record is not awaiting a sign.
 */
export async function signStatutoryRecord(
  recordId: string,
  associationId: string,
  signer: Approver,
): Promise<StatutoryRecord> {
  const record = await loadScoped(recordId, associationId);
  if (record.status !== "generated") {
    throw new StatutoryRecordError(
      `cannot sign a record in status "${record.status}"`,
      "INVALID_STATE",
      409,
    );
  }
  if (!record.agentActionId) {
    throw new StatutoryRecordError("record has no linked queue item to sign", "NO_ACTION", 409);
  }

  // The L3 approval IS the PM sign — recorded in the immutable agent-action
  // audit log by approveAction.
  await approveAction(record.agentActionId, associationId, signer);

  const [updated] = await db
    .update(statutoryRecords)
    .set({
      status: "signed",
      signedByUserId: signer.adminUserId,
      signedByEmail: signer.email,
      signedAt: new Date(),
      updatedAt: new Date(),
    })
    .where(and(eq(statutoryRecords.id, recordId), eq(statutoryRecords.associationId, associationId)))
    .returning();
  return updated;
}

/**
 * ISSUE the record — actuates THROUGH the L3 gate. `executeAction` refuses
 * (throwing) when the linked action is not `approved`, so an unsigned record
 * can never be issued. On success marks the record `issued`.
 */
export async function issueStatutoryRecord(
  recordId: string,
  associationId: string,
  actor: { actorType?: string; actorId?: string; actorEmail?: string },
): Promise<StatutoryRecord> {
  const record = await loadScoped(recordId, associationId);
  if (record.status === "issued") {
    throw new StatutoryRecordError("record already issued", "ALREADY_ISSUED", 409);
  }
  if (record.status === "rejected") {
    throw new StatutoryRecordError("record was rejected", "REJECTED", 409);
  }
  if (!record.agentActionId) {
    throw new StatutoryRecordError("record has no linked queue item to issue", "NO_ACTION", 409);
  }

  // THE L3 GATE: executeAction throws AgentActionError(APPROVAL_REQUIRED) when
  // the action is not approved — issuance without the PM sign is impossible.
  await executeAction(record.agentActionId, associationId, {
    actorType: actor.actorType ?? "human",
    actorId: actor.actorId,
    actorEmail: actor.actorEmail,
  });

  const [updated] = await db
    .update(statutoryRecords)
    .set({ status: "issued", issuedAt: new Date(), updatedAt: new Date() })
    .where(and(eq(statutoryRecords.id, recordId), eq(statutoryRecords.associationId, associationId)))
    .returning();
  return updated;
}

/** The PM declines the record. Rejects the linked queue item too. */
export async function rejectStatutoryRecord(
  recordId: string,
  associationId: string,
  signer: Approver,
  reason?: string,
): Promise<StatutoryRecord> {
  const record = await loadScoped(recordId, associationId);
  if (record.status === "issued") {
    throw new StatutoryRecordError("cannot reject an issued record", "ALREADY_ISSUED", 409);
  }
  const [updated] = await db
    .update(statutoryRecords)
    .set({
      status: "rejected",
      rejectedReason: reason ?? null,
      signedByUserId: signer.adminUserId,
      signedByEmail: signer.email,
      updatedAt: new Date(),
    })
    .where(and(eq(statutoryRecords.id, recordId), eq(statutoryRecords.associationId, associationId)))
    .returning();
  return updated;
}

/** Retrieve one record (tenant-scoped). */
export async function getStatutoryRecord(
  recordId: string,
  associationId: string,
): Promise<StatutoryRecord> {
  return loadScoped(recordId, associationId);
}

export interface ListStatutoryRecordsOptions {
  recordType?: StatutoryRecordType;
  statuses?: StatutoryRecord["status"][];
}

/** List an association's statutory records, most recent first. */
export async function listStatutoryRecords(
  associationId: string,
  opts: ListStatutoryRecordsOptions = {},
): Promise<StatutoryRecord[]> {
  const clauses = [eq(statutoryRecords.associationId, associationId)];
  if (opts.recordType) clauses.push(eq(statutoryRecords.recordType, opts.recordType));
  if (opts.statuses && opts.statuses.length > 0) {
    clauses.push(inArray(statutoryRecords.status, opts.statuses));
  }
  return db
    .select()
    .from(statutoryRecords)
    .where(and(...clauses))
    .orderBy(desc(statutoryRecords.createdAt));
}

/**
 * Near-deadline reminder sweep: records not yet issued/rejected whose statutory
 * deadline falls within `withinDays` from `now`, soonest deadline first. This is
 * the reminder that surfaces AHEAD of the deadline.
 */
export async function listStatutoryDeadlineReminders(
  associationId: string,
  withinDays = 5,
  now: Date = new Date(),
): Promise<StatutoryRecord[]> {
  const horizon = new Date(now.getTime() + withinDays * 24 * 60 * 60 * 1000);
  const rows = await db
    .select()
    .from(statutoryRecords)
    .where(
      and(
        eq(statutoryRecords.associationId, associationId),
        inArray(statutoryRecords.status, ["generated", "signed"]),
        lte(statutoryRecords.deadlineAt, horizon),
        gte(statutoryRecords.deadlineAt, new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000)),
      ),
    );
  return rows.sort((a, b) => a.deadlineAt.getTime() - b.deadlineAt.getTime());
}

export { AgentActionError };
